const fs = require("fs");
let content = fs.readFileSync("App.jsx", "utf8");

const replacements = {
  "Aula marcada como concluída! ✓": "¡Clase marcada como completada! ✓",
  "Aula desmarcada.": "Clase desmarcada.",
  "Anotação salva!": "¡Nota guardada!",
  "Aluno Premium": "Alumno Premium",
  "Início \\(Dashboard\\)": "Inicio (Dashboard)",
  "Painel Administrativo": "Panel Administrativo",
  "Sair da Conta": "Cerrar Sesión",
  "Mais Detalhes": "Más Detalles",
  "Acessar Conteúdo": "Acceder al Contenido",
  "Seus Treinamentos": "Tus Entrenamientos",
  "Produtos disponíveis": "Productos disponibles",
  "Disponível": "Disponible",
  "Acessar Curso": "Acceder al Curso",
  "Ver Detalhes": "Ver Detalles",
  "Novos Lançamentos": "Nuevos Lanzamientos",
  "Chegaram esta semana": "Llegaron esta semana",
  "Novo": "Nuevo",
  "Voltar": "Volver",
  "Você está assistindo:": "Estás viendo:",
  "% Concluído": "% Completado",
  "aulas concluídas": "clases completadas",
  "Conteúdo do Curso": "Contenido del Curso",
  "Vídeo em processamento ou não disponível": "Video procesándose o no disponible",
  "Marcar como concluída": "Marcar como completada",
  "Concluída": "Completada",
  "Anterior": "Anterior",
  "Próxima": "Siguiente",
  "Descrição": "Descripción",
  "Materiais Complementares": "Materiales Complementarios",
  "Anotações de Estudo": "Notas de Estudio",
  "Sobre o conteúdo": "Sobre el contenido",
  "Arquivos para baixar": "Archivos para descargar",
  "Baixar": "Descargar",
  "Suas Anotações": "Tus Notas",
  "Escreva suas reflexões ou pontos importantes da aula aqui...": "Escribe tus reflexiones o puntos importantes de la clase aquí...",
  "Salvar Anotação": "Guardar Nota",
  "Gerenciar Cursos": "Gestionar Cursos",
  "Gerenciar Aulas": "Gestionar Clases",
  "Nenhum curso selecionado": "Ningún curso seleccionado",
  "Upload de Vídeo": "Subir Video",
  "Link Externo": "Enlace Externo",
  "Adicionar URL do vídeo": "Añadir URL del video",
  "Upload em andamento...": "Subida en progreso...",
  "Selecionar Arquivo": "Seleccionar Archivo",
  "Salvar Aula": "Guardar Clase",
  "Garantia de 7 dias": "Garantía de 7 días",
  "Acesso Imediato": "Acceso Inmediato",
  "Acessar Agora": "Acceder Ahora",
  "Fechar": "Cerrar",
  "Aulas": "Clases",
  "Prosperidade": "Prosperidad",
  "Manifestação": "Manifestación",
  "A Chave do Poder": "La Llave del Poder",
  "O Chamado dos Números": "La Llamada de los Números",
  "Sussurro Fiel": "Susurro Fiel",
  "Fórmula para Reiniciar Mentalidade": "Fórmula para Reiniciar Mentalidad",
  "Numerologia": "Numerología",
  "Conexão Espiritual": "Conexión Espiritual",
  "Mentalidade": "Mentalidad",
  "Aula 1: A Ciência da Atração Mental": "Clase 1: La Ciencia de la Atracción Mental",
  "Aula 2: Limpando Ruídos Mentais e Bloqueios": "Clase 2: Limpiando Ruidos Mentales y Bloqueos",
  "Aula 3: Sintonizando a Frequência da Riqueza": "Clase 3: Sintonizando la Frecuencia de la Riqueza",
  "Aula 4: O Poder do Alinhamento Vibracional": "Clase 4: El Poder del Alineamiento Vibracional",
  "Aula 5: A Chave da Cocriação Ativa": "Clase 5: La Llave de la Co-creación Activa",
  "Entenda os fundamentos neurocientíficos e espirituais da lei da atração e como moldar sua realidade.": "Entiende los fundamentos neurocientíficos y espirituales de la ley de la atracción y cómo moldear tu realidad.",
  "Exercício de Visualização Ativa.pdf": "Ejercicio de Visualización Activa.pdf"
};

for (const [key, value] of Object.entries(replacements)) {
  const regex = new RegExp(key, "g");
  content = content.replace(regex, value);
}

fs.writeFileSync("App.jsx", content, "utf8");
console.log("Translation done.");
